### ISSUE TITLE
Server teleport on vsign

### ISSUE THREAD

**Issue by StianHanssen** [FastFelix771/TownyWands#2]
Hi! Just tried your plugin for the first time and it looks lovely!
However, while testing it I found a bug.
Unfortunately, as I clicked done after writing a name in "Add Friend" (/resgui), it teleported me to the second server in my Bungee network (which is also the lobby). This would happen every time vsign was involved.

Info:
- I had just installed the newest version (2.0.3) of your plugin.
- I had done no changes to the config at all
- I was not a part of a town while using the /resgui
- The towny configuration is almost default as well with the exception of allowing editing of the world in the wild.
- The server I tested it on is a part of a bungee network of two servers
- I use Spigot version 1.8.8
- I have no plugins that handles server teleportation. That is only done by bungee's /server
- I use Bungee Build #1116

There was no errors in the server console, but this message would pop up in my bungee console: http://pastie.org/private/zzldqcw8hwpehy3loyjega

I realize this may be a bug on bungee's end, however as you have had support for bungee (bungeetp) in previous versions, I assume you also made vsign working with bungee servers. Sorry, if I this is not a problem related to your plugin.

**Comment by OscarGLorenz** [comment]
Are you using ReActions or ProtocolLib?

**Comment by FastFelix771** [comment]
I dont think the plugin wanted to teleport you, it looks like you got kicked because of that error.
It's a protection mechanism of Netty. I'll work arround this soon, kicking someone is not a fix ._.
Bungeecord can teleport you to the fallback server if you got kicked from another server.

And yes, vsign should work with Bungeecord,
Im gonna setup some testservers with the builds you told me, thanks for your report :)

**Comment by FastFelix771** [comment]
I installed the same Bungeecord build as you and Spigot 1.8.8 and the vsigns worked perfect.

Are you using PaperSpigot by any chance? 
Or do you have some other packet-related plugins installed?

**Comment by StianHanssen** [comment]
I use normal spigot API version 1.8.8-R0.1-SNAPSHOT.

@ospa555 I do use ProtocolLib for my chat plugin

Being a plugin developer myself, I apologise for not being more thorough on testing, I don't have much time during the week. With the info provided I found the problem would occur when I had VentureChat (2.7.0) installed. VentureChat also depend on: MineverseChatAPI (1.0.0), ProtocolLib (3.6.4), PlaceholderAPI (1.9.0.1) and Vault (1.5.6), but none of them causes the kick.

Plugin links if you would like to test:
[Venturechat](https://www.spigotmc.org/resources/venturechat.771/download?version=66485), [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/download?version=56067), [MineverseChatAPI](https://www.spigotmc.org/resources/mineversechat-api.15833/download?version=62703), [Vault](http://dev.bukkit.org/media/files/894/359/Vault.jar), [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/download?version=33748)
(These are the proper download links from their pages by the way)

**Comment by FastFelix771** [comment]
Im fixing some bugs on the vSigns at the moment... its a little bit experimental ._. Packets <3
Im seriously thinking about adding (optional) ProtocolLib support... that would fix a ton of issues on ProtocolLib servers and probably adds support for a lot more versions.

**Comment by StianHanssen** [comment]
I think that is a good idea :) Good luck with the packets ^^

**Comment by FastFelix771** [comment]
Excellent timing! 
Just finished adding ProtocolLib support and a work-arround for the kicks caused by Netty.

I'll test a little bit and if everything works as expected, im gonna push out a new Update! :)

**Comment by StianHanssen** [comment]
Sorry to bring the bad news, but the problem seems to still be there. I used TownyWands v2.0.4 and still got the exact same message in bungee and the kick. I tried to look for messages by enabling debug, but nothing was said in chat, console nor on a file.

Problem should be reproducible with the following plugins installed:
Venturechat, PlaceholderAPI, MineverseChatAPI, Vault, ProtocolLib, Towny and TownyWands. You can have default configs. Same spigot and bungee version as said above.

Sorry for not being quicker with the testing

**Comment by FastFelix771** [comment]
If there was an error while handling a vSign, the debug mode would have told you.
And it also should no longer kick you... i'll test the plugins you listed here, one or more of them seems to be the error source.

**Comment by StianHanssen** [comment]
Hmm, I didn't get any message though :/ I did use the same button as in my first rapport. Screenshots: http://imgur.com/a/hnuCp

The source of the error is definitely the clash between VentureChat and TownyWands in my testing.

But if the case is not reproducible for you, please don't stress about it. I haven't even officially announced that we have a towny server at my community :)

**Comment by FastFelix771** [comment]
I tried it with the plugins and it didn't kick me out :/
Do you have any BungeeCord plugins running?

**Comment by StianHanssen** [comment]
Sorry, busy with university work until the evening. I will give you a list of bungee plugins then, and start some testing to see if any bungee plugins can be at fault as well.

**Comment by StianHanssen** [comment]
I have the following bungee plugins installed:
AlwaysOnline, BungeeAdminTools, BungeePexBrdige, BungeeTabListPlus, networkmessages, VentureChat, Yamler-Bungee

Try just installing VentureChat first, I still think that is the cause

**Comment by StianHanssen** [comment]
Alright, probabaly the last comment I will spam you with >.>
Here is a local test server that reproduces the bug: [Test Server](https://dl.dropboxusercontent.com/u/59521086/BungeeCord.zip)
Please tell me when you have downloaded the server so I can disable the link, don't want to distribute other's plugins.

Bungee plugins has nothing to do with it, the bungee proxy in the Test Server has no plugins. The spigot server has only the plugins involved with VentureChat and TownyWands.

Hopefully this will make it easier for you when testing :)

**Comment by FastFelix771** [comment]
It throws a 404 Error when im trying to download it :/

**Comment by StianHanssen** [comment]
Edit: Try the link now

**Comment by FastFelix771** [comment]
Okay, now it kicks me out, too.
And i think ive already found the issue... i'll check it out ;)
Could you report that error to the VentureChat Dev(s), too? 
That would help a lot! :)

**Comment by StianHanssen** [comment]
Sorry for late update. So I gave Aust1n46 the info and we had a look at it. Haven't found anything clear yet, however we saw that they problem would not occur on older bungee versions. I also saw ProtocolLib updated, that may fix it, I will try to get around to test it in the weekend :)

**Comment by FastFelix771** [comment]
Thank you, i also built in some new fixes for bugs on PaperSpigot Servers.
v2.0.5 will contain some quite nice stuff, if we find a work-arround for the newer bungeecord versions, i'll build it in before the Update!

**Comment by FastFelix771** [comment]
Just released v2.0.5! 
Check it out! ;)

Took me longer than expected, but its there.. hah real-life :3

**Comment by StianHanssen** [comment]
Awesome, thank you for the dedication to this report :)
I will try it out as soon as I can :)
