### ISSUE TITLE
Vsign not working anymore.

### ISSUE THREAD

**Issue by cherault76** [FastFelix771/TownyWands#3]
Hi ! Since the new version (1.10) virtual sign does not work, when I associate it with a command, the sign does not appear and nothing happen. And the raw command doesn't work too.

Example: I execute the following command /vsign {player} home {data}, nothing happen, and there is no error in the config too.

I tried with the debug mode and that changes nothing.
I don't know if I have do put another informations, If you need them I can give you.

**Comment by FastFelix771** [comment]
They probably changed some packet related stuff on 1.10 again... ill update TownyWands as soon as possible. :) Thanks for your report!

**Comment by FastFelix771** [comment]
Okay.. i indentified the issue. The version detector seems to be thinking its MC 1.1 instead of 1.10 - packets seems to be unchanged

**Comment by FastFelix771** [comment]
Fixed your issue and updated to 1.10.
http://dev.bukkit.org/bukkit-plugins/townywands/files/23-towny-wands-v2-0-9/
