### ISSUE TITLE
Warning in Console

### ISSUE THREAD

**Issue by HollishKid** [FastFelix771/TownyWands#4]
Hello,

I get the following warning spammed in console.

http://pastebin.com/jkeapMBP

Not sure whether this comes from this plugin, but I thought I'd report here anyway, since I think it might.
Thanks for your help!

**Comment by FastFelix771** [comment]
at **com.comphenix.protocol.injector**.netty.ChannelInjector.decode(ChannelInjector.java:522)
The error seems to be caused  by ProtocolLib.
Do you have any other Plugins that uses it?
And can you tell me your servers version and your ProtocolLib version?
