### ISSUE TITLE
Crash after use t deposit in resgui

### ISSUE THREAD

**Issue by Ectabro** [FastFelix771/TownyWands#5]
Hello,

Like i said in the title, i crash after use the t deposit. The sign appear, i wrote 50 for exemple, and when i press done, i'm sent to my lobby server. But in the console i can't see any error and the 50 was in my town.

Any idea ?

**Comment by FastFelix771** [comment]
Ive heard of such problems before ... are u using VentureChat? Is there any error in bungeecords console?

**Comment by Ectabro** [comment]
I don't use venturechat, but i didn't check for bungee.
In the config i put bungee to false

**Comment by FastFelix771** [comment]
Hmm, what are your versions of bungee / minecraft and TownyWands - Updating bungee helped the last guy with this Situation

**Comment by Ectabro** [comment]
I'm using spigot 1.9.2, with the last version of bungee and TownyWands 2.0.9

**Comment by FastFelix771** [comment]
I will test that out, today. Thanks

**Comment by Ectabro** [comment]
Thanks

**Comment by FastFelix771** [comment]
Last version of bungee? So BungeeCord for 1.10? Then i guess you are using ViaVersion or ProtocolSupport to connect 1.9.2 and 1.10?

You can also try out TownyWands 2.0.8 - it should work with 1.9 spigot - v2.0.9 was only tested with 1.10.2 so far

**Comment by Ectabro** [comment]
Okay after some check, we're running the the 1142 bungeecord build, and it's a 1.9 build, so it's okay.
I try the 2.0.8 and come back after

**Comment by Ectabro** [comment]
okay with the 2.0.8, and protocollib removed everithing work, maybe we just need to update bungeecord ?

**Comment by FastFelix771** [comment]
It _could_ help, but maybe 2.0.9 is just broken in 1.9 - i focused on 1.10 support on this build. But i will test and fix that.. its still meant to be compatible down to 1.6.4

Updating ProtocolLib could help a lot probably.

**Comment by Ectabro** [comment]
i have a test server with exactly the same plugin and version, juste bungee is missing, and everything work with townywands 2.0.9 and spigot 1.9.2, i think i'ts because of bungee

**Comment by FastFelix771** [comment]
Then updating Bungee is absolutely worth a try!

**Comment by Ectabro** [comment]
I test it tommorow morning ! 

Thanks for your help and for your wonderful plugin !

**Comment by FastFelix771** [comment]
So, was your test succesful?

**Comment by Ectabro** [comment]
With the last version of bungee, townywands 2.0.9 and protocollib 4.0.1, the sign appear but when i enter, nothing happen, i haven't error and when i click again on the gold  block for t deposit, nothing happe, no sign appear...

**Comment by FastFelix771** [comment]
Try with this one: http://ci.dmulloy2.net/job/ProtocolLib/301/ 
Its the very latest version of ProtocolLib (4.0.2) and should work with 1.9

I just tested it and it seems to work ._.
If that wont fix your problem, there must be a problem with BungeeCord... again... maybe i need to make an bungee plugin to solve that

**Comment by Ectabro** [comment]
I'm sorry but i can't install the last protocollib, because i'm on 1.9.2 :/

**Comment by FastFelix771** [comment]
I know, i tested it with 1.9.2 :)
Its backwards compatible

**Comment by Ectabro** [comment]
Sorry for the long time without answer, i have just tested TownyWands 2.0.9, the last version of bungee, and protocollib 4.0.2. 
When i click on the gold block, the sign appear, i enter 50 for exemple, and when i press done, nothing happen. After that, when i click again on the gold block nothing happen, and i haven't error in the console

**Comment by FastFelix771** [comment]
I guess i know the problem... the vsign probably doesnt show again because the last one is still waiting for an answer packet from your game... wich will never come. the question is: why?! it works without bungee, so there must be a problem between protocollib and bungeecord... i'll open an issue on ProtocolLibs Git repo, maybe comphenix or dmulloy2 haves an idea :(

**Comment by FastFelix771** [comment]
But there is also another way.. maybe.
Ive made some cleanup to the Packet Stuff since i dropped support for NMS and completely switched to ProtocolLib - and well.. _maybe_ it fixes your problem. The classes are much smaller now and therefore much less things can go wrong in theory.

**Comment by Ectabro** [comment]
I hope to !

**Comment by Ectabro** [comment]
So have you find a solution ?

**Comment by FastFelix771** [comment]
I think so.
Also, the vSign part has been split into its own module, for later use as an standalone plugin.
On 2.1.0, i need to finish the ingame editing thing first... i dont want to over complicate it with 1000 commands like PermissionsEx ._. On the other side, i need to bring in all the features, the config had...  :D

Well, i could try to create a hotfix with the 2.0.9 codebase, until i tested the new vSign module.
Hopefully that will work.

**Comment by Ectabro** [comment]
So cool ! :D

I'm excited to test it soon !

**Comment by FastFelix771** [comment]
For some reason, the version detection is broken -.-
It delays things more than i like... but i guess that will be fixed with the help of ProtocolLib.
And i was able to finally add support for MC 1.5 :3 But that still needs to be tested.

**Comment by Ectabro** [comment]
I'm still waiting, no problem :p

**Comment by FastFelix771** [comment]
https://services.unitygaming.de/jenkins/job/TownyWands/16/artifact/target/TownyWands-2.0.9-SNAPSHOT-shaded.jar
Take this jar and try it out! :) It works on 1.10 and 1.9, and with the bungeecord version i tested it.
If it doesnt solve your problem, thats really bad luck :c

The new vSign module seems to do a great job, i really hope it works for you!

**Comment by Ectabro** [comment]
I'm sorry but it's the same.. Nothing happen and no error in the console.

After that when i click on the gold block nothing happen

For info i'm using the last version of protocollib, 4.0.2 and for bungee the build #1167

**Comment by FastFelix771** [comment]
Dammit! BungeeCord really starts making me angry...
Is it possible for you to upgrade to 1.10 Spigot?

You could try switching the use-native-transport setting in your server.properties (if it still exists in 1.9)

**Comment by Ectabro** [comment]
I'll ugrade to 1.10 !

**Comment by FastFelix771** [comment]
:3 That hopefully works better.
I really suspect BungeeCords 1.10 to 1.9 "translation" mechanism to screw up my packets^^
Maybe its some kind of validation that filters them, i dont know :c

**Comment by FastFelix771** [comment]
Any update? Did it work on 1.10? :)

**Comment by FastFelix771** [comment]
Well, i assume everything works now on 1.10.
If you run into a problem, feel free to open a new issue! :)
