### ISSUE TITLE
BungeeCord / VentureChat netty-kick

### ISSUE THREAD

**Issue by bnussman** [FastFelix771/TownyWands#6]
Whenever I push Done when i am entering a value into a sign, I get disconnected from that spigot server and get sent to the hub of the bungee server. I get the following message in chat, and no errors in console. 
![capture](https://cloud.githubusercontent.com/assets/6440455/16772466/58d2137e-4822-11e6-84e6-2d8448e6942b.PNG)

**Comment by bnussman** [comment]
Here are my plugins on the server that disconnects me when i submit a value on a sign. 
![capture2](https://cloud.githubusercontent.com/assets/6440455/16772575/bffd1620-4822-11e6-9141-921d29434653.PNG)

**Comment by bnussman** [comment]
This is what it looks like when I am disconnected when i press 'done'. 
![capture3](https://cloud.githubusercontent.com/assets/6440455/16772757/68b072bc-4823-11e6-84ce-3a9574788788.PNG)

**Comment by bnussman** [comment]
This is the error in the Bungee console. It must be a Bungee issue? I am on the latest version of bungee too. (Build 1168)
![capture4](https://cloud.githubusercontent.com/assets/6440455/16772877/ca192e54-4823-11e6-9b63-4cdc8acd978b.PNG)

**Comment by FastFelix771** [comment]
VentureChat - for some reason its incompatible with TownyWands.
And there are also some general issues with ProtocolLib and BungeeCord, but this issue is probably caused because of VentureChat. Try with VentureChat disabled, if the issue is still there, i'll take a look whats wrong there. :)

**Comment by bnussman** [comment]
Well dang! I really need venture chat! But thanks for the support!

**Comment by FastFelix771** [comment]
https://github.com/FastFelix771/TownyWands/issues/2 This guy had the same problem, but only with special BungeeCord versions.
It was able to work with VentureChat with another version.. very strange things.

I was not able to find the true source of that issue, also author of VentureChat wasn't and i guess dmulloy2 would also send us to the BungeeCord authors. - There must be something in BungeeCord that screws up the SIGN_UPDATE packet.

You could try out some of the latest Bungee versions, maybe you find one that works... maybe not, but as long as i can't find the source of that bug, i can't do something against it. :(

But maybe it fixes itself with the full switch to ProtocolLibs API... i'll try to reproduce your problem with the very latest version i've created so far - maybe it magically starts to work.
