### ISSUE TITLE
vsign command does not accept multiple data strings

### ISSUE THREAD

**Issue by HollishKid** [FastFelix771/TownyWands#8]
Hello !

I'm a huge fan of your plugin. 
There is a little problem though, when using multiple {data} strings in the vsign command. When I use the second line of the sign, there is no space between the two words.

For example "time" on the first line and "day" on the second line only works if a use a space in front of the second line.

Could you change this ?

Thanks !

**Comment by FastFelix771** [comment]
Hi,

i know that you need to write spaces yourself.
I've made it like this to don't break commands or arguments, longer than 16 characters.

**Comment by HollishKid** [comment]
You've got a good point there ...

Thanks for the quick response !
